path_cloud_1: configs/data/14_21/cloud_1.ply
path_cloud_2: configs/data/14_21/cloud_2.ply

path_selections_1: configs/data/14_21/selections_1.json
path_selections_2: configs/data/14_21/selections_2.json
path_connections: configs/data/14_21/connections.json

gt: 
  GT_MIN: [27.5, 0.6]
  GT_MAX: [33.5, 0.6]

transformations:
  gt_1:
    - [-5.67377068e-01,-8.21570841e-01 ,-5.57190883e-02,  2.75497327e+01]
    - [ 8.16366973e-01,-5.70062881e-01 , 9.25919871e-02,  1.23605212e+00]
    - [-1.07834261e-01, 7.04734666e-03 , 9.94143907e-01,  5.47891145e-01]
    - [ 0.00000000e+00, 0.00000000e+00 , 0.00000000e+00,  1.00000000e+00]

  gt_2:
    - [-8.193119358583303979e-01, 5.729929066814765104e-01, -2.017547221981857292e-02, 5.034791622872137395e+01]
    - [-5.732025540919747364e-01, -8.193893600798627386e-01, 6.314730462515308340e-03, 4.702956969138702448e+01]
    - [-1.291327237655503710e-02, 1.673836684720698964e-02, 9.997764948098835092e-01, -1.093907201535025422e+02]
    - [ 0.000000000000000000e+00, 0.000000000000000000e+00, 0.000000000000000000e+00, 1.000000000000000000e+00]
